# Generated by Django 4.2.3 on 2023-07-04 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insured', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=255)),
                ('permium', models.IntegerField()),
                ('ternure', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policyholder.categorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insured.insurermodel')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policyholder.policymodel')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('Aproved', 'Aproved'), ('Denied', 'Denied')], default='Pending', max_length=255)),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insured.insurermodel')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policyholder.policymodel')),
            ],
        ),
    ]
