# Generated by Django 4.2.3 on 2023-07-08 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insured', '0001_initial'),
        ('policyholder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='insurer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insured.insurermodel'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='policyholder.policymodel'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='question',
            field=models.TextField(null=True),
        ),
    ]
