# Generated by Django 4.2.3 on 2023-07-08 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0002_alter_questionmodel_insurer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmodel',
            name='policy',
        ),
    ]
