# Generated by Django 4.2.3 on 2023-07-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0005_remove_policymodel_is_selected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policymodel',
            name='iS_selected',
        ),
        migrations.AddField(
            model_name='policymodel',
            name='is_selected',
            field=models.CharField(choices=[('Not Selected', 'Not Selected'), ('Selected', 'Selected')], default='Not Selected', max_length=255),
        ),
    ]
