# Generated by Django 4.2.3 on 2023-07-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0006_remove_policymodel_is_selected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policymodel',
            name='is_selected',
        ),
    ]
